### PR TITLE
Update library to 5.2

### PR DESCRIPTION
**Pull request by segadora**

### CODE REVIEW

**Comment by avramovic** [comment]
You need to update this to 5.* (my project currently uses 5.4) and @moon0326 needs to approve this PR :)

**Comment by segadora** [comment]
well, it seems like @moon0326 abandoned his project. I can consider upgrading it in my fork if you have a need for it.

**Comment by moon0326** [comment]
sorry guys.

Yeah, I haven't been using it much :) 

I will release a new version with this.

**Comment by moon0326** [comment]
okay, done. I will try to upgrade it to 5.4 over the weekend.

**Comment by avramovic** [comment]
I already used [aura/cli](https://github.com/auraphp/Aura.Cli) to make what I needed but yeah, you should upgrade it anyway because it can't be used if (another component is) already using versions > 5.1

**Comment by moon0326** [comment]
@avramovic I like that package as well :) FYI, v1.7 has 5.4.* illuminate packages.

**Pull request merged**
